# Generated by Django 3.1.5 on 2021-02-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hospital',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
